### ISSUE TITLE
Alert Bot Maintainer via Telegram on Errors

### ISSUE THREAD

**Issue by wanderingbort** [eosnetworkfoundation/telegram-bot#3]
Let's be honest, as soon as alerts are flowing to customers, the bot maintainer is gonna mute that Telegram group or channel. Nobody wants to get alerted for someone else's infrastructure all day just _in case_ there is a problem with the bot.

This pull request is to try to send errors the bot encounters directly to the maintainer on a best-effort basis. This will give the maintainer a chance of knowing when something is wrong without having to follow customer alerting channels.

## See Also
**engineering [issue 68](https://github.com/eosnetworkfoundation/engineering/issues/68) - EVM Monitoring and Alerting - Phase 1**
1. eos-evm [issue 602](https://github.com/eosnetworkfoundation/eos-evm/issues/602) - Funnel EVM Health Checks into CloudWatch
1. engineering [issue 48](https://github.com/eosnetworkfoundation/engineering/issues/48) - Collaborate with Operations on Unified Dashboarding Solution
1. engineering [issue 49](https://github.com/eosnetworkfoundation/engineering/issues/49) - Create Bot to Alert via IM on Specific Metrics
1. eos-evm [issue 603](https://github.com/eosnetworkfoundation/eos-evm/issues/603) - **SMS** Alerting for EVM Infrastructure Health Checks
1. engineering [issue 65](https://github.com/eosnetworkfoundation/engineering/issues/65) - **Email** Alerting for EVM Infrastructure Health Checks
1. telegram-bot [issue 1](https://github.com/eosnetworkfoundation/telegram-bot/issues/1) - Open-Source This Repo
1. engineering [issue 57](https://github.com/eosnetworkfoundation/engineering/issues/57) - Create Telegram Service Account
1. engineering [issue 58](https://github.com/eosnetworkfoundation/engineering/issues/58) - Create EVM **Testnet** Alert Channel Using Telegram Service Account
1. engineering [issue 64](https://github.com/eosnetworkfoundation/engineering/issues/64) - Create EVM **Mainnet** Alert Channel Using Telegram Service Account
1. engineering [issue 66](https://github.com/eosnetworkfoundation/engineering/issues/66) - Fix EVM CloudWatch Alerts
1. telegram-bot [issue 2](https://github.com/eosnetworkfoundation/telegram-bot/issues/2) - Human-Friendly Alerts
1. engineering [issue 71](https://github.com/eosnetworkfoundation/engineering/issues/71) - EVM Alerts for APAC Infrastructure
1. telegram-bot [issue 3](https://github.com/eosnetworkfoundation/telegram-bot/issues/3) - Alert Bot Maintainer via Telegram on Errors

**Comment by wanderingbort** [comment]
In testing now

**Comment by kj4ezj** [comment]
Done!

### Example
Here are two notifications the bot sent me when I generated two types of runtime errors.

![2023-10-02 17-45-09 - telegram-bot issue 3 example](https://github.com/eosnetworkfoundation/telegram-bot/assets/34947245/484b9a95-8fff-4966-88f5-967609fbf064)

The focus of this task is to minimize the time it takes an engineer to debug the system. It uses bright and colorful emoji to be visually distinctive, shows you the lambda name (use useful resource names), explains it is coming from a lambda, links you to the exact version of the code it is running, shows you what branch it came from (only if it did not come from a tag), shows you the stack trace (sanitized of secrets), and links you to the logs on CloudWatch. The message at the end is partially configurable, and the purpose is to help the customer get the attention of the maintainer because these alerts will go to the customer-facing channel if they cannot be delivered directly to the maintainer.
